# -*- coding: utf-8 -*-
"""24.09.04hello world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jmhJCEY30bmF5OjxnSQBMEDBSI-gR0Xd
"""

print("Hello World")

print("hello ")

print("3, 2, 1")

print("                    ")

import pylab as py

x_deg = py.arange(-180, 180+1,)
x_rad = py.deg2rad(x_deg)
y = py.sin(x_rad)

py.plot(x_deg, y)

py.xlabel('x(deg)')
py.ylabel('sin(x)')
py.grid(True)

